
services:
  # --- BACKEND (Laravel) ---
  app:
    build:
      context: .
      dockerfile: php/Dockerfile
    container_name: laravel-app
    working_dir: /var/www/html
    volumes:
      - ./support-ticket-system:/var/www/html # Map code Laravel 
    depends_on:
      - db

  queue:
    build:
      context: .
      dockerfile: php/Dockerfile
    container_name: laravel-queue
    working_dir: /var/www/html
    volumes:
      - ./support-ticket-system:/var/www/html
    depends_on:
      - db
      - app
    command: php artisan queue:work --sleep=3 --tries=3 --max-time=3600

  nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    ports:
      - "8000:80" # API sẽ chạy ở http://localhost:8000
    volumes:
      - ./support-ticket-system:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: support_ticket_system
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  # --- FRONTEND (React + Vite) ---
  frontend:
    image: node:20-alpine 
    container_name: react-frontend
    working_dir: /app
    ports:
      - "5173:5173" # Cổng mặc định của Vite
    volumes:
      - ./support-ticket-system-fe:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev -- --host" # Quan trọng: --host để mở cổng ra ngoài Docker

volumes:
  db_data: